import {useEffect,useMemo,useState} from 'react';
import {ResponsiveContainer,AreaChart,Area,BarChart,Bar,PieChart,Pie,Cell,XAxis,YAxis,CartesianGrid,Tooltip,Legend} from 'recharts';
import {api} from '../../api';
import './analytics.css';

const money=n=>'₹'+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2});
const num=n=>Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:1});
const colors=['#754747','#25856b','#c9963d','#7184a6','#c56b57','#9b8aab'];
const date=d=>d.toISOString().slice(0,10);
function range(preset){
  const now=new Date(Date.now()+19800000),end=new Date(date(now)),start=new Date(end);
  if(preset==='Yesterday'){start.setUTCDate(start.getUTCDate()-1);end.setUTCDate(end.getUTCDate()-1)}
  if(preset==='Last 7 Days')start.setUTCDate(start.getUTCDate()-6);
  if(preset==='Last 30 Days')start.setUTCDate(start.getUTCDate()-29);
  if(preset==='This Week')start.setUTCDate(start.getUTCDate()-(start.getUTCDay()+6)%7);
  if(preset==='This Month')start.setUTCDate(1);
  return {from:date(start),to:date(end)};
}
function Panel({title,note,action,children,wide=false,half=false}){return <section className={`an-panel ${wide?'an-wide':''} ${half?'an-half':''}`}><header><div><h2>{title}</h2>{note&&<p>{note}</p>}</div>{action}</header>{children}</section>}
function Toggle({value,onChange,options}){return <div className="an-toggle">{options.map(([key,label])=><button key={key} aria-pressed={value===key} className={value===key?'selected':''} onClick={()=>onChange(key)}>{label}</button>)}</div>}
function Empty(){return <div className="an-empty">No matching activity for this selection.</div>}
function Tip({active,payload,label}){if(!active||!payload?.length)return null;const p=payload[0].payload;return <div className="an-tooltip"><b>{p.name||p.date||label}</b>{payload.map((r,i)=><div key={i} style={{color:r.color}}>{r.name}: {['revenue','profit','stockValue','value','refund'].includes(r.dataKey)?money(r.value):num(r.value)}</div>)}{p.bills!==undefined&&<small>Bills: {num(p.bills)} · Quantity: {num(p.quantity)}</small>}</div>}
function Bars({data,metric='quantity',horizontal=false,stack=false}){return !data.length?<Empty/>:<div className="an-chart" style={{height:horizontal?Math.max(240,data.length*32):260}}><ResponsiveContainer width="100%" height="100%"><BarChart data={data} layout={horizontal?'vertical':'horizontal'} margin={{left:horizontal?5:0,right:15,top:10,bottom:5}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis type={horizontal?'number':'category'} dataKey={horizontal?undefined:'name'} tick={{fontSize:11}} tickFormatter={horizontal?num:undefined}/><YAxis type={horizontal?'category':'number'} dataKey={horizontal?'name':undefined} width={horizontal?125:55} tick={{fontSize:11}} tickFormatter={horizontal?v=>v.length>19?v.slice(0,18)+'…':v:num}/><Tooltip content={<Tip/>}/><Legend/><Bar dataKey={metric} name={metric==='quantity'?'Quantity sold':metric==='profit'?'Profit':metric==='returned'?'Returned quantity':metric==='bills'?'Bills':metric==='stockValue'?'Inventory value':'Revenue'} fill={colors[0]} radius={[4,4,4,4]} stackId={stack?'a':undefined}/>{stack&&<Bar dataKey="profit" name="Profit" fill={colors[1]} radius={[4,4,0,0]}/>}</BarChart></ResponsiveContainer></div>}
function Donut({data,metric='count',onClick,center}){return !data.some(r=>r[metric]>0)?<Empty/>:<div className="an-donut"><div className="an-chart" style={{height:220}}><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data.filter(r=>r[metric]>0)} dataKey={metric} nameKey="name" innerRadius={65} outerRadius={90} paddingAngle={3} onClick={r=>onClick?.(r.name)} style={{cursor:onClick?'pointer':'default'}}>{data.filter(r=>r[metric]>0).map((r,i)=><Cell key={r.name} fill={r.color||colors[i%colors.length]}/>)}</Pie><Tooltip formatter={v=>metric==='value'||metric==='revenue'?money(v):num(v)}/></PieChart></ResponsiveContainer><div className="an-donut-center">{center}</div></div><div className="an-legend">{data.map((r,i)=><button key={r.name} disabled={!onClick} onClick={()=>onClick?.(r.name)}><i style={{background:r.color||colors[i%colors.length]}}/><span>{r.name}</span><b>{metric==='value'||metric==='revenue'?money(r[metric]):num(r[metric])}</b></button>)}</div></div>}
const kpis=[['revenue','Net Sales Revenue',true],['profit','Gross Profit',true],['bills','Total Bills / Orders'],['quantity','Net Quantity Sold'],['average','Average Bill Value',true],['refund','Sales Return Amount',true],['inventory','Current Inventory Value',true],['slowValue','Slow Moving Stock Value',true],['lowStock','Low Stock Products'],['outStock','Out of Stock Products']];
const healthLabels={reorder:['High demand · Low stock','Reorder urgently'],healthy:['High demand · Healthy stock','Healthy / Monitor'],offer:['Low demand · Stock above minimum','Consider an offer / discount'],avoid:['Low demand · Low stock','Avoid purchasing more']};
export default function Analytics(){
  const [preset,setPreset]=useState('Last 7 Days'),[f,setF]=useState({...range('Last 7 Days'),category:'',brand:'',supplier:'',channel:'All',search:''});
  const [drill,setDrill]=useState({view:'all',page:1}),[rank,setRank]=useState('quantity'),[categoryMetric,setCategoryMetric]=useState('revenue'),[interval,setInterval]=useState('Daily'),[hourMetric,setHourMetric]=useState('revenue');
  const [data,setData]=useState(null),[busy,setBusy]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0);
  useEffect(()=>{const controller=new AbortController();setBusy(true);setError('');const timer=setTimeout(()=>{
    api('/analytics/overview?'+new URLSearchParams({...f,...drill,rank}),{signal:controller.signal}).then(r=>{setData(r);setBusy(false)}).catch(e=>{if(e.name!=='AbortError'){setError(e.message);setBusy(false)}});
    },300);return()=>{clearTimeout(timer);controller.abort()};},[f,drill,rank,retry]);
  const change=(key,value)=>{setF(old=>({...old,[key]:value}));setDrill({view:'all',page:1})};
  const open=(v)=>{setDrill({view:'all',page:1,...v});document.getElementById('movement-detail')?.scrollIntoView({behavior:'smooth',block:'start'})};
  const trend=useMemo(()=>{const map=new Map();for(const p of data?.trend||[]){const d=new Date(p.date);if(interval==='Weekly')d.setUTCDate(d.getUTCDate()-(d.getUTCDay()+6)%7);const key=interval==='Monthly'?p.date.slice(0,7):date(d);const row=map.get(key)||{date:key,revenue:0,profit:0,bills:0,quantity:0};for(const k of ['revenue','profit','bills','quantity'])row[k]+=p[k];map.set(key,row)}return [...map.values()]},[data,interval]);
  const options=data?.options;
  return <div className="analytics" aria-busy={busy}><div className="an-heading"><div><span className="an-eyebrow">BUSINESS INTELLIGENCE</span><h1>Analytics</h1><p>Sales performance, product demand and inventory health.</p></div><button className="btn ghost" onClick={()=>setRetry(x=>x+1)} disabled={busy}>{busy?'Updating…':'↻ Refresh'}</button></div>
    <div className="an-filters"><label>Date range<select aria-label="Date range" value={preset} onChange={e=>{setPreset(e.target.value);if(e.target.value!=='Custom Date Range'){setF(old=>({...old,...range(e.target.value)}));setDrill({view:'all',page:1})}}}>{['Today','Yesterday','Last 7 Days','Last 30 Days','This Week','This Month','Custom Date Range'].map(v=><option key={v}>{v}</option>)}</select></label>
      {['from','to'].map(k=><label key={k}>{k==='from'?'From':'To'}<input type="date" value={f[k]} onChange={e=>{setPreset('Custom Date Range');change(k,e.target.value)}}/></label>)}
      <label>Category<select aria-label="Category" value={f.category} onChange={e=>change('category',e.target.value)}><option value="">All categories</option>{options?.categories.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select></label>
      <label>Brand<select aria-label="Brand" value={f.brand} onChange={e=>change('brand',e.target.value)}><option value="">All brands</option>{options?.brands.map(v=><option key={v}>{v}</option>)}</select></label>
      <label>Supplier<select aria-label="Supplier" value={f.supplier} onChange={e=>change('supplier',e.target.value)}><option value="">All suppliers</option>{options?.suppliers.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select></label>
      <label>Sales channel<select aria-label="Sales channel" value={f.channel} onChange={e=>change('channel',e.target.value)}>{['All','POS','Online'].map(v=><option key={v}>{v}</option>)}</select></label><label>Product search<input placeholder="Product name or SKU" value={f.search} onChange={e=>change('search',e.target.value)}/></label></div>
    <p className="an-caption">Shop time: Asia/Kolkata · Inventory is current across all channels; sales and movement use the selected period and channel.</p>
    {error?<div className="alert" role="alert">{error} <button onClick={()=>setRetry(x=>x+1)}>Retry</button></div>:busy&&!data?<div className="an-skeleton" role="status" aria-label="Loading analytics">{Array.from({length:10},(_,i)=><div key={i}/>)}<p>Updating analytics…</p></div>:data&&<>
      <div className="an-kpis">{kpis.map(([key,label,currency])=>{const value=data.overview[key],prev=data.previous[key],delta=prev?((value-prev)/Math.abs(prev))*100:null;return <article className="an-kpi" key={key}><span>{label}</span><strong>{currency?money(value):num(value)}</strong>{prev!==undefined?<small className={delta===null||delta===0?'':(key==='refund'?delta<0:delta>0)?'positive':'negative'}>{delta===null?(value===0?'No change':'New activity'):delta===0?'No change':`${delta>0?'↑':'↓'} ${num(Math.abs(delta))}%`} <em>vs previous {data.meta.days} days</em></small>:<small>Current stock · {key==='slowValue'?'sell-through below 50%':'at purchase cost / stock level'}</small>}</article>})}</div>
      <Panel title="Needs Attention" note="Select an insight to inspect the matching products."><div className="an-insights">{data.insights.map(r=><button key={r.title} onClick={()=>open({view:r.view||'all',...(r.health?{health:r.health}:{}),...(r.movement?{movement:r.movement}:{})})}><span>{r.title}</span><b>{r.money?money(r.value):r.value}</b><small>View products →</small></button>)}</div></Panel>
      <div className="an-grid"><Panel wide title="Sales Trend" note="Net revenue and gross profit, after returns" action={<Toggle value={interval} onChange={setInterval} options={['Daily','Weekly','Monthly'].map(v=>[v,v])}/>}><div className="an-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend} margin={{right:16,top:15}}><defs><linearGradient id="anRevenue" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={colors[0]} stopOpacity={0.25}/><stop offset="100%" stopColor={colors[0]} stopOpacity={0.01}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date" tick={{fontSize:11}} minTickGap={30}/><YAxis tickFormatter={num} width={65} tick={{fontSize:11}}/><Tooltip content={<Tip/>}/><Legend/><Area type="monotone" dataKey="revenue" name="Revenue" stroke={colors[0]} fill="url(#anRevenue)" strokeWidth={2.5}/><Area type="monotone" dataKey="profit" name="Profit" stroke={colors[1]} fill="transparent" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></Panel>
      <Panel title="Stock Movement" note="Quantity-based sell-through"><Donut data={data.stockMovement} onClick={name=>open({movement:name})} center={<><b>{num(data.stockMovement.reduce((s,r)=>s+r.count,0))}</b><small>products</small></>}/></Panel>
      <Panel wide title="Top Selling Products" note="Top 10 products in the selected period" action={<Toggle value={rank} onChange={setRank} options={['quantity','revenue','profit'].map(v=>[v,v[0].toUpperCase()+v.slice(1)])}/>}><Bars data={data.top} metric={rank} horizontal/><div className="an-table"><table><thead><tr><th>Product</th><th>Qty</th><th>Revenue</th><th>Profit</th><th>Stock</th></tr></thead><tbody>{data.top.map(p=><tr key={p.id}><td>{p.name}</td><td>{num(p.quantity)}</td><td>{money(p.revenue)}</td><td>{money(p.profit)}</td><td>{num(p.stock)}</td></tr>)}</tbody></table></div></Panel>
      <Panel title="Category Performance" action={<Toggle value={categoryMetric} onChange={setCategoryMetric} options={['quantity','revenue','profit'].map(v=>[v,v[0].toUpperCase()+v.slice(1)])}/>}><Bars data={data.categories.slice(0,10)} metric={categoryMetric} horizontal/><div className="an-table"><table><thead><tr><th>Category</th><th>Qty</th><th>Revenue</th><th>Profit</th><th>Stock value</th></tr></thead><tbody>{data.categories.map(p=><tr key={p.name}><td>{p.name}</td><td>{num(p.quantity)}</td><td>{money(p.revenue)}</td><td>{money(p.profit)}</td><td>{money(p.stockValue)}</td></tr>)}</tbody></table></div></Panel>
      {['fast','slow'].map(view=><Panel half key={view} title={view==='fast'?'Fast Moving Products':'Slow Moving Stock'} note={view==='fast'?'Ranked by net quantity, then sell-through':'Lowest sell-through first · Current stock above zero'} action={<button className="an-link" onClick={()=>open({view})}>View all →</button>}>{!data[view].length?<Empty/>:data[view].map(p=><div className="an-product" key={p.id}><div><b>{p.name}</b><small>{num(p.quantity)} sold · {num(p.stock)} remaining · {view==='fast'?money(p.revenue)+' revenue':money(p.stockValue)+' locked'}</small></div><div><strong>{num(p.sellThrough)}%</strong><progress max="100" value={p.sellThrough}/><small className={p.reorder?'negative':''}>{p.reorder?'HIGH DEMAND – REORDER':p.status}</small></div></div>)}</Panel>)}
      <Panel wide title="Stock Health / Demand Matrix" note="High demand: sell-through ≥ 50% with positive sales. Low stock: current stock ≤ configured minimum."><div className="an-health">{data.health.map(r=><button className={r.name} key={r.name} onClick={()=>open({health:r.name})}><span>{healthLabels[r.name][0]}</span><b>{r.count}<small> products</small></b><p>{healthLabels[r.name][1]} →</p></button>)}</div></Panel>
      <Panel title="Inventory Value" note="Current stock × current purchase price"><Donut data={data.stockMovement} metric="value" center={<><b>{money(data.overview.inventory)}</b><small>current value</small></>}/></Panel>
      <Panel wide title="Supplier Performance" note="Attributed to each product’s latest purchasing supplier; this is not stock-lot attribution."><Bars data={data.suppliers.slice(0,10)} metric="revenue" stack/><div className="an-table"><table><thead><tr><th>Supplier</th><th>Purchased</th><th>Sold</th><th>Sell-through</th><th>Revenue</th><th>Profit</th><th>Stock value</th></tr></thead><tbody>{data.suppliers.map(p=><tr key={p.name}><td>{p.name}</td><td>{num(p.purchased)}</td><td>{num(p.quantity)}</td><td>{num(p.sellThrough)}%</td><td>{money(p.revenue)}</td><td>{money(p.profit)}</td><td>{money(p.stockValue)}</td></tr>)}</tbody></table></div></Panel>
      <Panel title="Sales Channels" note="Finalized POS invoices / Delivered online orders"><Donut data={data.channels.map(r=>({...r,revenue:Math.max(0,r.revenue)}))} metric="revenue"/>{data.channels.map(r=><div className="an-product" key={r.name}><div><b>{r.name}</b><small>{num(r.bills)} bills / orders · {num(r.quantity)} items</small></div><div><strong>{money(r.revenue)}</strong><small>Average {money(r.average)}</small></div></div>)}</Panel>
      <Panel title="Sales by Hour" note="Shop time · Transactions and refunds in the selected period" action={<Toggle value={hourMetric} onChange={setHourMetric} options={ [['revenue','Revenue'],['bills','Bills']]}/>}><Bars data={data.hourly.map(r=>({...r,name:`${String(r.hour).padStart(2,'0')}:00`}))} metric={hourMetric}/></Panel>
      <Panel wide title="Sales Returns" note="Recorded on return date; original invoices remain intact."><div className="an-return-stats"><span><b>{num(data.returns.count)}</b>Returns</span><span><b>{money(data.returns.amount)}</b>Refund amount</span><span><b>{num(data.returns.quantity)}</b>Returned quantity</span><span><b>{data.returns.percentage===null?'—':num(data.returns.percentage)+'%'}</b>Returns / gross quantity sold</span></div><Bars data={data.returns.top} metric="returned" horizontal/></Panel></div>
      <div id="movement-detail"><Panel title="Stock Movement & Reorder Detail" note="Available = max(0, net sold) + current stock. Net sold = sold − returns in the selected period; purchase quantity is informational." action={<button className="an-link" onClick={()=>setDrill({view:'all',page:1})}>Reset drill-down</button>}><div className="an-detail-filter"><label>Products<select value={drill.view} onChange={e=>setDrill({view:e.target.value,page:1})}><option value="all">All products</option><option value="top">Top performer</option><option value="fast">Fast / good moving</option><option value="slow">Slow moving stock</option><option value="low">Low / out of stock</option></select></label><span>{drill.movement|| (drill.health?healthLabels[drill.health][0]:'')} · {num(data.products.total)} products</span></div><div className="an-table"><table><thead><tr>{['Product','Category / Brand','Available','Purchased','Sold','Returned','Net sold','Current stock','Sell-through','Movement','Purchase price','Stock value','Avg qty / day','Demand','Reorder'].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{data.products.rows.map(p=><tr key={p.id}><td><b>{p.name}</b><small>{p.sku}</small></td><td>{p.category}<small>{p.brand||'Unassigned'}</small></td><td>{num(p.available)}</td><td>{num(p.purchased)}</td><td>{num(p.grossQty)}</td><td>{num(p.returned)}</td><td>{num(p.quantity)}</td><td>{num(p.stock)}</td><td>{num(p.sellThrough)}%<progress max="100" value={p.sellThrough}/></td><td><span className="an-badge" style={{background:data.stockMovement.find(r=>r.name===p.status)?.color}}>{p.status}</span></td><td>{money(p.purchasePrice)}</td><td>{money(p.stockValue)}</td><td>{num(p.average)}</td><td>{p.demand}</td><td className={p.reorder?'negative':''}>{p.reorder?'REORDER REQUIRED':'Monitor'}</td></tr>)}</tbody></table>{!data.products.rows.length&&<Empty/>}</div><div className="an-pagination"><button disabled={data.products.page<=1} onClick={()=>setDrill(d=>({...d,page:d.page-1}))}>Previous</button><span>Page {data.products.page} of {Math.max(1,Math.ceil(data.products.total/25))}</span><button disabled={data.products.page*25>=data.products.total} onClick={()=>setDrill(d=>({...d,page:d.page+1}))}>Next</button></div></Panel></div>
      <details className="an-method"><summary>How these figures are calculated</summary><p>Revenue excludes tax, delivery charges and rounding, and includes allocated bill discounts. POS cost uses invoice purchase-price snapshots; online cost uses current purchase prices because historical costs are not stored. Online orders are counted once, only when delivered, using their order creation date. Returns use their processing date, so a period can have negative net sales or a return rate above 100%.</p><p>Sell-through = max(0, net quantity sold) ÷ (max(0, net quantity sold) + max(0, current stock)) × 100. Returns are already restocked by the existing returns flow. Fast ≥80%, good ≥50%, slow ≥20%, very slow &gt;0%, not moving 0%. Inventory is a live snapshot, including stock reserved by pending online orders. Historical opening stock is not inferred from today’s stock. Demand levels follow the same thresholds. A high-demand product at or below its minimum stock needs reorder.</p><p>Supplier attribution uses the latest recorded purchase for a product. It does not split mixed supplier stock or reconstruct historical supplier ownership. Product, category, brand and supplier filters select the inventory scope; channel filters select sales activity against that shared inventory.</p></details>
    </>}
  </div>;
}
